export NVARCH="${NVARCH}";
export CUDA_VERSION="${CUDA_VERSION}";
export CUDA_VERSION_MAJOR="${CUDA_VERSION_MAJOR}";
export CUDA_VERSION_MINOR="${CUDA_VERSION_MINOR}";
export CUDA_VERSION_PATCH="${CUDA_VERSION_PATCH}";
