name: feature-matrix

description: Determine the feature matrix

inputs:
  base_sha:
    type: string
    default: ""
  full_matrix:
    type: string
    default: false
  file_patterns:
    type: string
    default: ""

outputs:
  features:
    value: ${{ steps.matrix.outputs.features }}
  scenarios:
    value: ${{ steps.matrix.outputs.scenarios }}

runs:
  using: composite
  steps:
    - id: changes
      name: Check if files changed
      if: inputs.full_matrix != 'true'
      uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1
      with:
        base_sha: "${{ inputs.base_sha }}"
        since_last_remote_commit: "${{ inputs.base_sha == '' && 'true' || 'false' }}"
        files: |
          features/src/**
          ${{ inputs.file_patterns }}

    - name: Report changes
      if: inputs.full_matrix != 'true'
      shell: bash
      run: echo '${{ toJSON(steps.changes.outputs) }}'

    - name: Determine the feature matrix
      id: matrix
      shell: bash
      run: |
        bash --noprofile --norc -x -eo pipefail \
          .github/actions/feature-matrix/action.sh \
          '${{ inputs.full_matrix }}' \
          '${{ steps.changes.outputs.all_changed_and_modified_files }}' \
        | tee -a $GITHUB_OUTPUT;
