name: image-matrix

description: Determine the image matrix

inputs:
  base_sha:
    type: string
    default: ""
  features:
    type: string
    required: false
  scenarios:
    type: string
    required: false
  full_matrix:
    type: string
    default: true
  file_patterns:
    type: string
    default: ""

outputs:
  linux:
    value: ${{ steps.matrix.outputs.linux }}
  windows:
    value: ${{ steps.matrix.outputs.windows }}

runs:
  using: composite
  steps:
    - id: changes
      name: Check if files changed
      if: inputs.full_matrix != 'true'
      uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1
      with:
        base_sha: "${{ inputs.base_sha }}"
        since_last_remote_commit: "${{ inputs.base_sha == '' && 'true' || 'false' }}"
        files: |
          matrix.yml
          windows/**
          image/.devcontainer/*
          ${{ inputs.file_patterns }}

    - name: Report changes
      if: inputs.full_matrix != 'true'
      shell: bash
      run: echo '${{ toJSON(steps.changes.outputs) }}'

    - name: Determine the image matrix
      id: matrix
      shell: bash
      run: |
        bash --noprofile --norc -x -eo pipefail \
          .github/actions/image-matrix/action.sh \
          '${{ inputs.full_matrix }}' \
          '${{ inputs.features || '[]' }}' \
          '${{ inputs.scenarios || '[]' }}' \
          '${{ steps.changes.outputs.all_changed_and_modified_files }}' \
        | tee -a $GITHUB_OUTPUT;
