export NVHPC="${NVHPC}";
export NVHPC_VERSION="${NVHPC_VERSION}";
export NVHPC_VERSION_MAJOR="${NVHPC_VERSION_MAJOR}";
export NVHPC_VERSION_MINOR="${NVHPC_VERSION_MINOR}";
export NVHPC_ROOT="${NVHPC_ROOT}";
export NVHPC_MODULEFILE_DIRS=${NVHPC_MODULEFILE_DIRS};

if [ -z "${LIBRARY_PATH:-}" ] \
|| [ -n "${LIBRARY_PATH##*"${NVHPC_CUDA_HOME}/lib64/stubs"*}" ]; then
    export LIBRARY_PATH="${NVHPC_CUDA_HOME}/lib64/stubs${LIBRARY_PATH:+:$LIBRARY_PATH}"
fi
