name: setup-runner-env

description: Setup self-hosted runner environment

runs:
  using: composite
  steps:
    - name: Dump environment
      shell: bash -eo pipefail {0}
      run: | # zizmor: ignore[template-injection]
        echo "env: ${{ toJSON(env) }}"
        echo "runner: '${{ toJSON(runner) }}'"

    - if: runner.environment != 'self-hosted'
      name: Free up disk space
      uses: ./.github/actions/free-disk-space
      with:
        tool_cache: "${{ runner.tool_cache }}"

    - if: runner.environment == 'self-hosted'
      name: Setup self-hosted runner environment
      shell: bash -eo pipefail {0}
      run: | # zizmor: ignore[github-env]
        echo "HOME=$RUNNER_WORKSPACE" >> "$GITHUB_ENV";
        echo "TMPDIR=$RUNNER_TEMP" >> "$GITHUB_ENV";

    - if: runner.environment == 'self-hosted'
      name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: '24'

    - if: runner.environment != 'self-hosted'
      name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

    - name: Create docker context
      shell: bash
      run: docker context create builder

    - if: runner.environment != 'self-hosted'
      name: Setup docker buildx on github-hosted runners
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      with:
        buildkitd-flags: --debug
        endpoint: builder

    - if: runner.environment == 'self-hosted'
      name: Setup docker buildx on self-hosted runners
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      with:
        buildkitd-flags: --debug --config /etc/buildkit/buildkitd.toml
        endpoint: builder
        buildkitd-config: /etc/buildkit/buildkitd.toml
