name: setup-runner-env

description: Setup self-hosted runner environment

runs:
  using: composite
  steps:
    - name: Dump environment
      shell: bash -eo pipefail {0}
      run: | # zizmor: ignore[template-injection]
        echo "env: ${{ toJSON(env) }}"
        echo "runner: '${{ toJSON(runner) }}'"

    - if: runner.environment != 'self-hosted'
      name: Free up disk space
      uses: ./.github/actions/free-disk-space
      with:
        tool_cache: "${{ runner.tool_cache }}"

    - if: runner.environment == 'self-hosted'
      name: Setup self-hosted runner environment
      shell: bash -eo pipefail {0}
      run: | # zizmor: ignore[github-env]
        echo "HOME=$RUNNER_WORKSPACE" >> "$GITHUB_ENV";
        echo "TMPDIR=$RUNNER_TEMP" >> "$GITHUB_ENV";

    - if: runner.environment == 'self-hosted'
      name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '20'

    - if: runner.environment != 'self-hosted'
      name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

    - name: Create docker context
      shell: bash
      run: docker context create builder

    - if: runner.environment != 'self-hosted'
      name: Setup docker buildx on github-hosted runners
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      with:
        buildkitd-flags: --debug
        endpoint: builder

    - if: runner.environment == 'self-hosted'
      name: Setup docker buildx on self-hosted runners
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      with:
        buildkitd-flags: --debug --config /etc/buildkit/buildkitd.toml
        endpoint: builder
        buildkitd-config: /etc/buildkit/buildkitd.toml
