name: devcontainer-json

description: Make .devcontainer.json

inputs:
  os:
    type: string
    required: true
  features:
    type: string
    required: true
  container_env:
    type: string
    required: false
  syft_ver:
    type: string
    required: false
    default: latest

outputs:
  tag:
    value: ${{ steps.json.outputs.tag }}

runs:
  using: composite
  steps:

    - id: json
      name: Make image/.devcontainer/devcontainer.json
      shell: bash
      run: |
        bash --noprofile --norc -x -eo pipefail       \
          .github/actions/devcontainer-json/action.sh \
          '${{ inputs.os }}'                          \
          '${{ inputs.features }}'                    \
          '${{ inputs.container_env }}'               \
          '${{ inputs.syft_ver }}'                \
        3>> "$GITHUB_OUTPUT"                          \
        4> image/.devcontainer/devcontainer.json.out  ;

        mv image/.devcontainer/devcontainer.json{.out,};

        echo "tag=${tag}";
        echo -n "devcontainer=";
        cat "image/.devcontainer/devcontainer.json"
