name: Build and test devcontainer images

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
        description: Image OS
      repo:
        type: string
        required: true
        description: Image repo
      push:
        type: string
        required: false
        default: false
        description: Whether to push the image
      features:
        type: string
        required: true
        description: JSON list of devcontainer features
      container_env:
        type: string
        required: false
        description: JSON map of default envvars to build into the devcontainer

jobs:

  build-test-and-push:
    name: ${{ matrix.edition }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { edition: "2022", runner: "${{ github.repository != 'rapidsai/devcontainers' && 'windows-2022' || 'windows-amd64-cpu4' }}" }
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: info
        name: Get container info
        shell: bash
        env:
          INPUT_REPO: ${{ inputs.repo }}
          INPUT_OS: ${{ inputs.os }}
          MATRIX_EDITION: ${{ matrix.edition }}
          INPUT_FEATURES: ${{ inputs.features }}
        run: |
          repo="$INPUT_REPO";
          cl="$(echo "$INPUT_FEATURES" | jq -r '.[1].version')";
          cuda="$(echo "$INPUT_FEATURES" | jq -r '.[0].version')";
          version="$(git describe --abbrev=0 --tags | sed 's/[a-zA-Z]//g' | cut -d '.' -f -2)";
          base_tag="cuda${cuda}-cl${cl}";
          tag_without_os="${version}-${base_tag}";
          cat <<EOF | tee "$GITHUB_OUTPUT"
          cl=${cl}
          cuda=${cuda}
          repo=${repo,,}
          version=${version}
          base_tag=${base_tag}
          tag_without_os=${tag_without_os}
          tag=${tag_without_os}-${INPUT_OS}${MATRIX_EDITION}
          EOF

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER || vars.DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN || secrets.DOCKERHUB_TOKEN }}

      - name: Build ${{ steps.info.outputs.tag }}
        uses: ./.github/actions/build-windows-image
        with:
          cl: "${{ steps.info.outputs.cl }}"
          tag: "${{ steps.info.outputs.tag }}"
          cuda: "${{ steps.info.outputs.cuda }}"
          repo: "${{ steps.info.outputs.repo }}"
          version: "${{ steps.info.outputs.version }}"
          edition: "${{ matrix.edition }}"

      - name: Test ${{ steps.info.outputs.tag }}
        uses: ./.github/actions/test-windows-image
        with:
          cl: "${{ steps.info.outputs.cl }}"
          tag: "${{ steps.info.outputs.tag }}"
          cuda: "${{ steps.info.outputs.cuda }}"
          repo: "${{ steps.info.outputs.repo }}"
          version: "${{ steps.info.outputs.version }}"
          edition: "${{ matrix.edition }}"

      - if: inputs.push == 'true'
        name: Push ${{ steps.info.outputs.tag }}
        shell: powershell
        env:
          REPO: ${{ steps.info.outputs.repo }}
          TAG: ${{ steps.info.outputs.tag }}
          TAG_WITHOUT_OS: ${{ steps.info.outputs.tag_without_os }}
        run: |
          docker image tag ${env:REPO}:${env:TAG} ${env:REPO}:${env:TAG_WITHOUT_OS}
          docker push ${env:REPO}:${env:TAG_WITHOUT_OS}
          docker push ${env:REPO}:${env:TAG}

      - if: inputs.push == 'true' && github.ref_name == 'main'
        name: Push latest-${{ steps.info.outputs.base_tag }}
        shell: powershell
        env:
          REPO: ${{ steps.info.outputs.repo }}
          TAG: ${{ steps.info.outputs.tag }}
          BASE_TAG: ${{ steps.info.outputs.base_tag }}
          INPUT_OS: ${{ inputs.os }}
          MATRIX_EDITION: ${{ matrix.edition }}
        run: |
          docker image tag ${env:REPO}:${env:TAG} ${env:REPO}:latest-${env:BASE_TAG}-${env:INPUT_OS}${env:MATRIX_EDITION}
          docker image tag ${env:REPO}:${env:TAG} ${env:REPO}:latest-${env:BASE_TAG}
          docker push ${env:REPO}:latest-${env:BASE_TAG}-${env:INPUT_OS}${env:MATRIX_EDITION}
          docker push ${env:REPO}:latest-${env:BASE_TAG}
