name: Release Linux

concurrency:
  group: release-linux-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      syft_ver:
        description: "Syft version for SBOM generation"
        required: false
        default: latest

jobs:

  features-matrix:
    name: Determine features matrix
    runs-on: ubuntu-latest
    outputs:
      features: "${{ steps.matrix.outputs.features }}"
      scenarios: "${{ steps.matrix.outputs.scenarios }}"
    steps:
      - name: "Checkout ${{ github.repository }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Copy common scripts into features
        uses: ./.github/actions/copy-common-scripts

      - id: matrix
        name: Determine features matrix
        uses: ./.github/actions/feature-matrix
        with:
          full_matrix: true

  image-matrix:
    name: Determine image matrix
    needs: features-matrix
    runs-on: ubuntu-latest
    outputs:
      linux: ${{ steps.matrix.outputs.linux }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: matrix
        name: Determine image matrix
        uses: ./.github/actions/image-matrix
        with:
          features: "${{ needs.features-matrix.outputs.features }}"
          scenarios: "${{ needs.features-matrix.outputs.scenarios }}"
          full_matrix: true

  release-linux:
    if: needs.image-matrix.outputs.linux != '{"include":[]}'
    name: ${{ matrix.name }}
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-test-and-push-linux-image.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-matrix.outputs.linux) }}
    with:
      push: true
      os: "${{ matrix.os }}"
      features: "${{ toJSON(matrix.features) }}"
      container_env: "${{ toJSON(matrix.env) }}"
      repo: "${{ vars.DOCKERHUB_REPOSITORY || github.repository }}"
      syft_ver: "${{ inputs.syft_ver || 'latest' }}"
